name: Docker Image CI

on: [push]

jobs:

  build:
    strategy:
      matrix:
        ubuntu_release: ["18.04", "19.10"]
    env: 
      RPY2_VERSION: master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build base image
      run: |
        docker build base \
          --tag rpy2/base-ubuntu:"${RPY2_VERSION}"-"${{ matrix.ubuntu_release }}" \
          --build-arg RPY2_VERSION="${RPY2_VERSION}" \
          --build-arg UBUNTU_RELEASE="${{ matrix.ubuntu_release }}"
    - name: Push base image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        IMAGE_TAG=rpy2/base-ubuntu:"${RPY2_VERSION}"-"${{ matrix.ubuntu_release }}"
        docker tag "${IMAGE_TAG}" "${IMAGE_TAG}"
        docker push "${IMAGE_TAG}"
    - name: Build jupyter image
      run: |
        docker build jupyter \
          --tag rpy2/jupyter-ubuntu:"${RPY2_VERSION}"-"${{ matrix.ubuntu_release }}" \
          --build-arg RPY2_VERSION="${RPY2_VERSION}" \
          --build-arg UBUNTU_RELEASE="${{ matrix.ubuntu_release }}"
    - name: Push jupyter image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        IMAGE_TAG=rpy2/jupyter-ubuntu:"${RPY2_VERSION}"-"${{ matrix.ubuntu_release }}"
        docker tag "${IMAGE_TAG}" "${IMAGE_TAG}"
        docker push "${IMAGE_TAG}"
    - name: Build jupyter_ds image
      run: |
        docker build jupyter_ds \
          --tag rpy2/jupyter_ds-ubuntu:"${RPY2_VERSION}"-"${{ matrix.ubuntu_release }}" \
          --build-arg RPY2_VERSION="${RPY2_VERSION}" \
          --build-arg UBUNTU_RELEASE="${{ matrix.ubuntu_release }}"
    - name: Push jupyter_ds image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        IMAGE_TAG=rpy2/jupyter_ds-ubuntu:"${RPY2_VERSION}"-"${{ matrix.ubuntu_release }}"
        docker tag "${IMAGE_TAG}" "${IMAGE_TAG}"
        docker push "${IMAGE_TAG}"
 
