name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image base
      env:
        UBUNTU_RELEASE: 19.04
        RPY2_VERSION: master
      run: |
        cd base && \
        docker build . \
          --tag rpy2/base-ubuntu:$(date +%s)-19.04 \
          --build-arg RPY2_VERSION="${RPY2_VERSION}" \
          --build-arg UBUNTU_RELEASE="${UBUNTU_RELEASE}"
 
